// The glossary: a breadth-first set of CS/programming/networking terms, cross-linked to each other and to
// lessons. Mirrors curriculum.js conventions (a data array + pure helpers; no framework). The <Term>
// component and the site-wide popup read `termsMap`; the /glossary/ page reads `terms` + the helpers.
//
// Each term: { slug, term, category, short, body, related[], lessons[] }
//   slug    — kebab id; the #anchor on the glossary page and the data-term value
//   short   — one line, shown in the hover/focus popup
//   body    — a couple of sentences, shown on the glossary page
//   related — other term slugs (interlinks)
//   lessons — lesson slugs (reuse curriculum.js lessonBySlug to render "appears in" links)
//
// CATEGORY_ORDER drives the section order on the page.

export const CATEGORY_ORDER = ["programming", "data", "networking", "complexity"];
export const CATEGORY_LABELS = {
  programming: "Programming",
  data: "Data & representation",
  networking: "Networks & the internet",
  complexity: "Algorithms & complexity",
};

export const terms = [
  // ---- programming ----
  { slug: "variable", term: "Variable", category: "programming",
    short: "A named place that refers to a value; the name can be re-pointed at a new value.",
    body: "A variable is a name bound to a value. It is not a box that remembers everything you put in it — reassigning the name simply points it at a new value, and the old one is gone unless another name still holds it.",
    related: ["value", "assignment", "name-binding"], lessons: ["values"] },
  { slug: "value", term: "Value", category: "programming",
    short: "A piece of data a program computes with — a number, some text, True or False.",
    body: "Every value has a type that decides what you can do with it. Values are what expressions evaluate to and what variables refer to.",
    related: ["variable", "data-type"], lessons: ["values"] },
  { slug: "name-binding", term: "Name binding", category: "programming",
    short: "Attaching a name to a value with `=`; rebinding moves the name, it doesn't change the old value.",
    body: "Binding a name with `=` makes it refer to a value. Binding it again moves the name to a new value; if you need the old one later, save it under another name first.",
    related: ["variable", "assignment", "aliasing"], lessons: ["values"] },
  { slug: "data-type", term: "Data type", category: "programming",
    short: "The kind of a value (int, float, str, bool) — it decides which operations are allowed.",
    body: "The type of a value, not how it looks, decides what an operator does: \"3\" + \"4\" joins text, while 3 + 4 adds numbers. The four core types a beginner meets are int, float, str, and bool.",
    related: ["integer", "float", "string", "boolean"], lessons: ["datatypes", "conversion"] },
  { slug: "integer", term: "Integer (int)", category: "programming",
    short: "A whole number with no fractional part, like 13 or -4.",
    body: "Integers count things and index positions. In Python they have unlimited size (no overflow), unlike fixed-width integers in hardware.",
    related: ["float", "floor-division", "overflow"], lessons: ["datatypes", "overflow"] },
  { slug: "float", term: "Floating-point (float)", category: "programming",
    short: "A number with a fractional part, like 3.5 — stored in binary, so some values are approximate.",
    body: "Floats represent fractional numbers but in binary, so values like 0.1 can't be stored exactly. That is why 0.1 + 0.2 isn't quite 0.3 and why you shouldn't compare floats with ==.",
    related: ["integer", "true-division", "roundoff"], lessons: ["datatypes", "roundoff"] },
  { slug: "string", term: "String (str)", category: "programming",
    short: "Text — a sequence of characters in quotes, like \"racecar\".",
    body: "Strings are sequences you can index and slice, and they are immutable: \"changing\" a string actually makes a new one.",
    related: ["immutable", "index", "slice"], lessons: ["palindrome"] },
  { slug: "boolean", term: "Boolean (bool)", category: "programming",
    short: "A value that is either True or False.",
    body: "Booleans are what comparisons produce and what conditions test. In Python True and False also act as 1 and 0 numerically.",
    related: ["comparison", "truthiness", "boolean-operator"], lessons: ["comparison", "booleanops"] },
  { slug: "operator", term: "Operator", category: "programming",
    short: "A symbol that combines values: + - * / // % ** for maths, == < > for comparison.",
    body: "Operators act on values to produce new ones. Which operation happens depends on the operands' types and on precedence.",
    related: ["operator-precedence", "modulo", "exponent"], lessons: ["arithmetic"] },
  { slug: "expression", term: "Expression", category: "programming",
    short: "Any piece of code that evaluates to a value, like 2 + 3 or x > 0.",
    body: "Expressions compute values; statements do things. A comparison like age >= 18 is an expression that evaluates to a Boolean.",
    related: ["value", "operator", "comparison"], lessons: ["arithmetic"] },
  { slug: "operator-precedence", term: "Operator precedence", category: "programming",
    short: "The order operators run in: × and ÷ happen before + and −, regardless of left-to-right.",
    body: "Python follows the usual maths order, not strict left-to-right, so 2 + 3 * 4 is 14, not 20. Parentheses override it when you mean the addition first.",
    related: ["operator", "expression"], lessons: ["arithmetic"] },
  { slug: "floor-division", term: "Floor division (//)", category: "programming",
    short: "Division that throws away the remainder and returns a whole number.",
    body: "7 // 2 is 3, not 3.5 — the fraction is discarded. Useful for counting whole groups; the wrong choice when you want an average.",
    related: ["true-division", "modulo", "integer"], lessons: ["datatypes"] },
  { slug: "true-division", term: "True division (/)", category: "programming",
    short: "Division that keeps the fraction and returns a float.",
    body: "7 / 2 is 3.5. A single slash always yields a float in Python, even when the numbers divide evenly.",
    related: ["floor-division", "float"], lessons: ["datatypes"] },
  { slug: "modulo", term: "Modulo (%)", category: "programming",
    short: "The remainder after division; it wraps values around (clock arithmetic, even/odd).",
    body: "10 % 3 is 1. Modulo powers wrap-around (15 o'clock becomes 3), parity tests (n % 2 == 0 means even), and cycling through positions.",
    related: ["floor-division", "overflow"], lessons: ["modulo", "overflow", "fizzbuzz"] },
  { slug: "exponent", term: "Exponent (**)", category: "programming",
    short: "Raising to a power: 2 ** 3 is 8. In Python `^` is NOT power — it is bitwise XOR.",
    body: "Use ** for powers. The `^` symbol many languages and spreadsheets use for powers is bitwise XOR in Python, so 2 ^ 3 silently gives 1.",
    related: ["operator"], lessons: ["exponent"] },
  { slug: "assignment", term: "Assignment (=)", category: "programming",
    short: "Binds a value to a name. Not the same as == (which compares).",
    body: "`=` stores a value in a name; `==` asks whether two values are equal. Using `=` where a condition expects `==` is a classic mix-up (in Python it's a syntax error).",
    related: ["comparison", "name-binding"], lessons: ["values", "comparison"] },
  { slug: "comparison", term: "Comparison", category: "programming",
    short: "An operator like == or > that produces a Boolean (True/False) you can store and reuse.",
    body: "A comparison is itself a value. age >= 18 evaluates to True or False, which you can keep in a variable or use directly in an `if`. Watch the boundary: > excludes the endpoint, >= includes it.",
    related: ["boolean", "assignment", "equality"], lessons: ["comparison", "roundoff"] },
  { slug: "equality", term: "Equality (==)", category: "programming",
    short: "Tests whether two values are equal; distinct from assignment (=).",
    body: "== returns a Boolean. Beware: a list never equals True, and floats rarely compare equal exactly — prefer a tolerance for floats.",
    related: ["comparison", "truthiness", "roundoff"], lessons: ["comparison", "roundoff"] },
  { slug: "boolean-operator", term: "Boolean operator (and / or / not)", category: "programming",
    short: "Combine conditions. `or` returns one of its operands, not always a tidy True/False.",
    body: "`x == 1 or 2` is read as (x == 1) or 2 and yields the truthy 2 — not what you meant. Compare against each value in full: x == 1 or x == 2.",
    related: ["boolean", "truthiness", "comparison"], lessons: ["booleanops"] },
  { slug: "truthiness", term: "Truthiness", category: "programming",
    short: "Any value can act as True or False in a condition; empty/zero/None are \"falsy\", the rest \"truthy\".",
    body: "`if items:` asks whether items is truthy — a non-empty list is. But a list never equals True, so `if items == True:` quietly fails. The falsy values are 0, 0.0, \"\", [], {}, and None.",
    related: ["boolean", "none", "boolean-operator"], lessons: ["truthiness"] },
  { slug: "conditional", term: "Conditional (if)", category: "programming",
    short: "Runs a block of code only when a condition is true.",
    body: "An `if` chooses whether to run its block. Two separate `if`s are two independent decisions — both can run; use `if/else` (or `elif`) when only one should.",
    related: ["branch", "elif-ladder", "boolean"], lessons: ["ifelse"] },
  { slug: "branch", term: "Branch", category: "programming",
    short: "One path through a conditional; if/elif/else pick exactly one to run.",
    body: "Each arm of an if/elif/else is a branch. Exactly one runs, chosen top-to-bottom by the first true condition.",
    related: ["conditional", "elif-ladder"], lessons: ["ifelse", "elifladder"] },
  { slug: "elif-ladder", term: "elif ladder", category: "programming",
    short: "A chain of elifs; the first true branch wins, so the order of the tests is the logic.",
    body: "Because the first matching branch wins and the rest are skipped, a grading ladder must test the strictest band first — put the loosest first and the strict branches become unreachable.",
    related: ["branch", "conditional"], lessons: ["elifladder"] },
  { slug: "loop", term: "Loop", category: "programming",
    short: "Code that repeats — a `for` over a sequence or a `while` on a condition.",
    body: "Loops do the same work for each item or until a condition changes. Never delete from a list while looping over it — the positions shift under you.",
    related: ["iteration", "range", "accumulator"], lessons: ["accumulate", "filter"] },
  { slug: "iteration", term: "Iteration", category: "programming",
    short: "One pass through a loop body.",
    body: "Each time around the loop is an iteration, usually with the loop variable bound to the next item or index.",
    related: ["loop", "range"], lessons: ["accumulate", "search"] },
  { slug: "range", term: "range()", category: "programming",
    short: "Produces integers to loop over; range(n) is 0..n-1 — the end is excluded.",
    body: "range(len(nums)) yields each valid index. The exclusive end is a common off-by-one trap: range(5) stops at 4.",
    related: ["loop", "index"], lessons: ["search", "binary"] },
  { slug: "accumulator", term: "Accumulator", category: "programming",
    short: "A variable that builds up a result across a loop — a running total or list.",
    body: "Start it at a base (0 for a sum, [] for a list) and update it each pass with += or append. Using = instead of += overwrites instead of accumulating.",
    related: ["loop", "list"], lessons: ["accumulate", "runningmax"] },
  { slug: "function", term: "Function", category: "programming",
    short: "A named, reusable block that takes inputs and hands back a value with `return`.",
    body: "A function packages an idea you can call. It opens its own scope, runs, and returns a value; a function that forgets to `return` hands back None.",
    related: ["parameter", "return-value", "scope"], lessons: ["functions"] },
  { slug: "parameter", term: "Parameter", category: "programming",
    short: "A name in a function definition that receives an argument when the function is called.",
    body: "Parameters are the function's inputs. Arguments fill them by position (left to right) unless you name them, so argument order matters.",
    related: ["argument", "function"], lessons: ["parameters"] },
  { slug: "argument", term: "Argument", category: "programming",
    short: "A value passed into a function call; positional arguments fill parameters left to right.",
    body: "remaining(30, 100) binds the first parameter to 30 and the second to 100. Naming them — remaining(budget=100, spent=30) — makes the intent unmissable.",
    related: ["parameter", "function"], lessons: ["parameters"] },
  { slug: "return-value", term: "Return value", category: "programming",
    short: "What a function hands back; a function with no `return` hands back None.",
    body: "`return` ends the function and gives a value to the caller. Computing the answer but forgetting to return it is a classic bug — the work happens, nothing comes out.",
    related: ["function", "none"], lessons: ["functions"] },
  { slug: "scope", term: "Scope", category: "programming",
    short: "The region where a name is visible; a function's locals live in its own frame.",
    body: "Names created inside a function are local to it and vanish when it returns. The call stack tracks which frame's names are currently in view.",
    related: ["function", "call-stack"], lessons: ["functions"] },
  { slug: "call-stack", term: "Call stack", category: "programming",
    short: "The stack of active function frames; a call pushes a frame, a return pops it.",
    body: "Each call adds a frame with its own locals; returning removes it. The stack is how a program remembers where to go back to, and how recursion keeps its many copies apart.",
    related: ["function", "scope", "recursion"], lessons: ["functions"] },
  { slug: "recursion", term: "Recursion", category: "programming",
    short: "A function that calls itself, each call a new frame, until a base case stops it.",
    body: "Recursion solves a problem in terms of a smaller version of itself. Without a base case that stops the calls, it never ends.",
    related: ["function", "call-stack"], lessons: ["functions"] },
  { slug: "list", term: "List", category: "programming",
    short: "An ordered, mutable collection of values, written [1, 2, 3].",
    body: "Lists hold a sequence you can index, slice, and grow with append. Being mutable, a list can be changed through any name that shares it.",
    related: ["index", "slice", "mutable", "aliasing"], lessons: ["filter", "partition", "rainwater"] },
  { slug: "index", term: "Index", category: "programming",
    short: "A position in a sequence, starting at 0; s[0] is the first item.",
    body: "Indices number items from 0. Negative indices count from the end (s[-1] is the last). Going past the end is an error.",
    related: ["list", "slice", "range"], lessons: ["search", "palindrome"] },
  { slug: "slice", term: "Slice", category: "programming",
    short: "A sub-sequence like s[1:3]; the end index is excluded, and s[:] makes a copy.",
    body: "Slicing reads part of a sequence without changing it. s[:] (or list(s)) is the idiom for copying a list so changes don't alias the original.",
    related: ["index", "list", "aliasing"], lessons: ["aliasing", "filter"] },
  { slug: "mutable", term: "Mutable", category: "programming",
    short: "Can be changed in place (lists, dicts); changes are seen through every name that shares it.",
    body: "Mutating a list affects all of its aliases. That is powerful and dangerous: backup = scores doesn't copy, so changing scores changes backup too.",
    related: ["immutable", "aliasing", "list"], lessons: ["aliasing", "partition"] },
  { slug: "immutable", term: "Immutable", category: "programming",
    short: "Cannot be changed in place (ints, strings, tuples); \"changing\" one makes a new value.",
    body: "Immutable values are safe from aliasing surprises: name = name.upper() makes a new string and rebinds the name; the original is untouched.",
    related: ["mutable", "string", "integer"], lessons: ["aliasing"] },
  { slug: "aliasing", term: "Aliasing", category: "programming",
    short: "Two names pointing at the same object, so changing it through one is seen through the other.",
    body: "Assignment binds another name to the same object; it does not copy. Equal object ids reveal the sharing. To get an independent copy of a list, slice it (scores[:]).",
    related: ["reference", "mutable", "slice"], lessons: ["aliasing", "partition"] },
  { slug: "reference", term: "Reference", category: "programming",
    short: "What a name actually holds — a pointer to an object, not a private copy.",
    body: "Variables refer to objects. When two names reference one mutable object, they are aliases; this is the mechanism behind aliasing bugs.",
    related: ["aliasing", "mutable"], lessons: ["aliasing", "partition"] },
  { slug: "comprehension", term: "List comprehension", category: "programming",
    short: "A one-expression loop that builds a list, like [n for n in nums if n > 10].",
    body: "A comprehension is concise shorthand for a build-a-new-list loop. Python still runs it as a loop internally; the finished list appears at the end.",
    related: ["list", "loop"], lessons: ["filter"] },
  { slug: "none", term: "None", category: "programming",
    short: "Python's \"no value\"; what a function returns when it has no `return`.",
    body: "None is a real value meaning \"nothing here\". It is falsy, and it is what you get back from a function that computed something but forgot to return it.",
    related: ["truthiness", "return-value"], lessons: ["functions", "truthiness"] },
  { slug: "syntax-error", term: "Syntax error", category: "programming",
    short: "Code the interpreter can't parse at all, so it never runs (e.g. `if x = 5`).",
    body: "A syntax error is caught before the program runs. It differs from a logic bug, where the code runs fine but produces the wrong answer.",
    related: ["assignment"], lessons: [] },
  { slug: "sentinel", term: "Sentinel value", category: "programming",
    short: "A stand-in value (like -1 for \"not found\") that can't be mistaken for a real answer.",
    body: "Linear search starts found at -1: no real index is negative, so -1 unambiguously means \"not found yet\".",
    related: ["index"], lessons: ["search"] },

  // ---- data & representation ----
  { slug: "bit", term: "Bit", category: "data",
    short: "The smallest unit of data: a single 0 or 1.",
    body: "Everything a computer stores is bits. Combining bits in place-value columns (powers of two) represents numbers, text, and more.",
    related: ["byte", "binary", "place-value"], lessons: ["binary"] },
  { slug: "byte", term: "Byte", category: "data",
    short: "A group of 8 bits; can represent 256 different values (0–255).",
    body: "A byte is the usual unit of storage. An 8-bit counter wraps from 255 back to 0 — that's overflow.",
    related: ["bit", "overflow"], lessons: ["overflow"] },
  { slug: "binary", term: "Binary", category: "data",
    short: "Base-two numbers: each column is a power of two (1, 2, 4, 8, …).",
    body: "Binary is place value in base two. To write 13, fill the columns biggest-to-smallest: 8 + 4 + 1 = 1101. To read it back, double and add.",
    related: ["bit", "place-value", "decimal"], lessons: ["binary", "bindecimal"] },
  { slug: "place-value", term: "Place value", category: "data",
    short: "Each column is worth a power of the base; binary doubles, decimal multiplies by ten.",
    body: "The same digit means different amounts in different columns. Walking columns in the right order (big to small) is what makes base conversion work.",
    related: ["binary", "decimal"], lessons: ["binary", "bindecimal"] },
  { slug: "decimal", term: "Decimal", category: "data",
    short: "Base-ten numbers: columns are 1, 10, 100, …",
    body: "The everyday number system. Mixing up base ten and base two is the classic binary-to-decimal bug (reading 1101 as eleven hundred).",
    related: ["binary", "place-value"], lessons: ["bindecimal"] },
  { slug: "hexadecimal", term: "Hexadecimal", category: "data",
    short: "Base-sixteen numbers (0–9 then A–F); a compact way to write bytes.",
    body: "Each hex digit packs four bits, so a byte is two hex digits. It's common for colours and memory addresses.",
    related: ["binary", "byte"], lessons: [] },
  { slug: "ascii", term: "ASCII", category: "data",
    short: "A code that maps characters to numbers so text can be stored as bits.",
    body: "ASCII assigns each letter and symbol a number (A is 65). It's why text is just numbers under the hood.",
    related: ["bit", "string"], lessons: [] },
  { slug: "overflow", term: "Overflow", category: "data",
    short: "When a fixed-width number runs out of room and wraps around (255 → 0 in 8 bits).",
    body: "Hardware integers have a fixed number of bits, so they wrap like a clock. Python's integers have no fixed width, so they grow instead of overflowing.",
    related: ["byte", "modulo", "integer"], lessons: ["overflow"] },
  { slug: "roundoff", term: "Round-off error", category: "data",
    short: "Small errors from storing fractional numbers in binary — why 0.1 + 0.2 ≠ 0.3.",
    body: "Most decimals can't be represented exactly in binary floating-point, so arithmetic accumulates tiny errors. Compare floats with a tolerance, not ==.",
    related: ["float", "equality"], lessons: ["roundoff"] },
  { slug: "compression", term: "Compression", category: "data",
    short: "Storing data in fewer bits by exploiting patterns or redundancy.",
    body: "Compression shrinks data for storage or transfer. Lossless compression reconstructs the original exactly; lossy compression trades some fidelity for size.",
    related: ["run-length-encoding", "lossless", "lossy"], lessons: ["rle"] },
  { slug: "run-length-encoding", term: "Run-length encoding (RLE)", category: "data",
    short: "Compress repeats by storing (count, value) pairs instead of each item.",
    body: "A row like RRRGG becomes (3, R)(2, G). It's a simple, lossless scheme — and forgetting to emit the final run is a classic bug.",
    related: ["compression", "lossless"], lessons: ["rle"] },
  { slug: "lossless", term: "Lossless", category: "data",
    short: "Compression that can rebuild the original data exactly, bit for bit.",
    body: "Lossless schemes (like RLE or ZIP) lose nothing — the decompressed data is identical to the original. Required for text and code.",
    related: ["compression", "lossy"], lessons: ["rle"] },
  { slug: "lossy", term: "Lossy", category: "data",
    short: "Compression that discards some detail to save more space (JPEG, MP3).",
    body: "Lossy schemes throw away information the eye or ear is unlikely to miss, achieving smaller sizes than lossless — but the original can't be perfectly recovered.",
    related: ["compression", "lossless"], lessons: [] },

  // ---- networks & the internet ----
  { slug: "internet", term: "Internet", category: "networking",
    short: "The global network of networks that carries data between computers.",
    body: "The internet is the physical-and-logical plumbing: cables, routers, and addressing that move packets worldwide. The Web is one thing built on top of it.",
    related: ["world-wide-web", "internet-vs-web", "packet"], lessons: ["routing"] },
  { slug: "world-wide-web", term: "World Wide Web (WWW)", category: "networking",
    short: "The system of linked pages and sites you browse — built on top of the internet.",
    body: "The Web is web pages and links served over HTTP. It runs on the internet but is not the same thing: email and video calls use the internet without using the Web.",
    related: ["internet", "internet-vs-web", "http", "url"], lessons: [] },
  { slug: "internet-vs-web", term: "Internet vs Web", category: "networking",
    short: "The internet is the network; the Web is one service (linked pages) running on it.",
    body: "People say \"the internet\" when they often mean \"the Web\". The internet is the delivery network; the Web, email, and streaming are services that ride on it.",
    related: ["internet", "world-wide-web"], lessons: [] },
  { slug: "protocol", term: "Protocol", category: "networking",
    short: "An agreed set of rules two computers follow so they can understand each other.",
    body: "Protocols define the format and order of messages. HTTP, DNS, and IP are protocols, each handling a different job in moving and interpreting data.",
    related: ["http", "ip-address", "dns"], lessons: [] },
  { slug: "http", term: "HTTP", category: "networking",
    short: "The protocol browsers use to request web pages from servers.",
    body: "HyperText Transfer Protocol is the request/response language of the Web: your browser asks a server for a page, the server replies with it.",
    related: ["https", "world-wide-web", "url", "server"], lessons: [] },
  { slug: "https", term: "HTTPS", category: "networking",
    short: "HTTP with encryption, so others can't read or tamper with the traffic.",
    body: "The S is for secure: HTTPS wraps HTTP in encryption, protecting passwords and data in transit. The padlock in the address bar means HTTPS.",
    related: ["http", "protocol"], lessons: [] },
  { slug: "url", term: "URL", category: "networking",
    short: "A web address — it names the protocol, the host, and the path to a resource.",
    body: "A URL like https://example.com/page bundles the protocol (https), the host (example.com, resolved by DNS), and the path (/page).",
    related: ["http", "dns", "world-wide-web"], lessons: [] },
  { slug: "dns", term: "DNS", category: "networking",
    short: "The Domain Name System — translates names like example.com into IP addresses.",
    body: "Computers route by numeric IP address, but people use names. DNS is the internet's phone book, looking up the IP for a name before a connection is made.",
    related: ["ip-address", "url", "protocol"], lessons: ["routing"] },
  { slug: "ip-address", term: "IP address", category: "networking",
    short: "A numeric address that identifies a computer on a network, like 142.250.72.14.",
    body: "Every device on the internet has an IP address so packets can be delivered to it. DNS exists to turn human names into these numbers.",
    related: ["dns", "packet", "routing"], lessons: ["routing"] },
  { slug: "packet", term: "Packet", category: "networking",
    short: "A small chunk of data with addressing, the unit the internet actually moves.",
    body: "Messages are split into packets, each routed independently and reassembled in order at the destination. Packets can take different paths and arrive out of order.",
    related: ["packet-switching", "routing", "reassembly"], lessons: ["routing", "multipacket"] },
  { slug: "packet-switching", term: "Packet switching", category: "networking",
    short: "Breaking data into packets that each find their own way across the network.",
    body: "Rather than reserving one fixed line, packet switching sends independent packets that routers forward hop by hop. It's efficient and resilient to failures.",
    related: ["packet", "routing", "fault-tolerance"], lessons: ["routing", "multipacket"] },
  { slug: "routing", term: "Routing", category: "networking",
    short: "Choosing the path a packet takes from node to node toward its destination.",
    body: "Routers forward each packet one hop closer to its destination. Because routing is per-hop, the network can reroute around a failed node.",
    related: ["router", "packet", "fault-tolerance"], lessons: ["routing", "faulttolerance"] },
  { slug: "router", term: "Router", category: "networking",
    short: "A device that forwards packets between networks toward their destination.",
    body: "Routers are the junctions of the internet, reading each packet's destination and passing it to the next hop along a good path.",
    related: ["routing", "packet"], lessons: ["routing"] },
  { slug: "server", term: "Server", category: "networking",
    short: "A computer that provides a service (like web pages) to clients that ask for it.",
    body: "Servers wait for requests and respond — a web server returns pages over HTTP. The requesting computer is the client.",
    related: ["client", "http"], lessons: [] },
  { slug: "client", term: "Client", category: "networking",
    short: "A computer (or app, like a browser) that requests a service from a server.",
    body: "Your browser is a client: it sends requests to servers and displays the responses. The client/server split organises most internet services.",
    related: ["server", "http"], lessons: [] },
  { slug: "bandwidth", term: "Bandwidth", category: "networking",
    short: "How much data a connection can carry per second — its capacity.",
    body: "Bandwidth is the width of the pipe (e.g. 100 Mbps). It limits throughput but is distinct from latency, the delay before data starts arriving.",
    related: ["latency"], lessons: [] },
  { slug: "latency", term: "Latency", category: "networking",
    short: "The delay before data starts arriving — how long a round trip takes.",
    body: "Latency is the lag, measured in milliseconds; bandwidth is the capacity. A high-bandwidth link can still feel slow if its latency is high.",
    related: ["bandwidth"], lessons: [] },
  { slug: "reassembly", term: "Reassembly", category: "networking",
    short: "Putting packets back in order at the destination using their sequence numbers.",
    body: "Because packets can arrive out of order, each carries a sequence number so the receiver can rebuild the original message correctly.",
    related: ["packet", "packet-switching"], lessons: ["multipacket"] },
  { slug: "fault-tolerance", term: "Fault tolerance", category: "networking",
    short: "A system's ability to keep working when part of it fails.",
    body: "A redundant network reroutes around a dead node; a single-path one strands the packet. Fault tolerance comes from having more than one way through.",
    related: ["routing", "packet-switching"], lessons: ["faulttolerance"] },

  // ---- algorithms & complexity ----
  { slug: "algorithm", term: "Algorithm", category: "complexity",
    short: "A step-by-step procedure for solving a problem.",
    body: "An algorithm is the recipe a program follows. The same problem often has several algorithms that differ in clarity and speed.",
    related: ["time-complexity", "big-o"], lessons: ["search"] },
  { slug: "time-complexity", term: "Time complexity", category: "complexity",
    short: "How an algorithm's running time grows as the input gets bigger.",
    body: "Complexity describes scaling, not a stopwatch time: it asks how the work grows with input size n. It's the basis for comparing algorithms.",
    related: ["big-o", "linear-time", "exponential-time"], lessons: [] },
  { slug: "big-o", term: "Big-O notation", category: "complexity",
    short: "A shorthand for how an algorithm scales, ignoring constants — O(n), O(n²), O(2ⁿ).",
    body: "Big-O captures the dominant growth term. O(n) doubles when the input doubles; O(n²) quadruples; O(2ⁿ) explodes. It's how the gap between approaches is named.",
    related: ["time-complexity", "polynomial-time", "exponential-time"], lessons: [] },
  { slug: "constant-time", term: "Constant time (O(1))", category: "complexity",
    short: "Work that doesn't grow with input size — the same cost no matter how big n is.",
    body: "Looking up a list item by index is constant time. It's the gold standard: the input can grow without the cost growing.",
    related: ["big-o", "linear-time"], lessons: [] },
  { slug: "linear-time", term: "Linear time (O(n))", category: "complexity",
    short: "Work that grows in step with the input — twice the data, twice the time.",
    body: "Scanning every item once, like linear search, is linear time. Predictable and usually fine, but slower than constant time for big inputs.",
    related: ["big-o", "constant-time", "polynomial-time"], lessons: ["search"] },
  { slug: "polynomial-time", term: "Polynomial time", category: "complexity",
    short: "Running time that grows like n raised to a fixed power — n, n², n³ …",
    body: "Polynomial-time algorithms (linear, quadratic, …) are considered tractable: doubling the input multiplies the work by a fixed factor, not an exploding one.",
    related: ["big-o", "linear-time", "exponential-time"], lessons: [] },
  { slug: "exponential-time", term: "Exponential time", category: "complexity",
    short: "Running time that doubles with each extra input — O(2ⁿ); blows up fast.",
    body: "Exponential algorithms become unusable quickly: adding one item doubles the work. The jump from polynomial to exponential is the line between feasible and infeasible.",
    related: ["polynomial-time", "big-o"], lessons: [] },
  { slug: "parallelism", term: "Parallelism", category: "complexity",
    short: "Doing several pieces of work at the same time on multiple workers.",
    body: "Parallelism splits work across workers to finish sooner. It only helps for work that can run independently — and only up to the limit set by dependencies.",
    related: ["speedup", "dependency-chain"], lessons: ["speedup"] },
  { slug: "speedup", term: "Speedup", category: "complexity",
    short: "How many times faster a parallel run is than the sequential one: sequential ÷ parallel.",
    body: "Two workers can halve the time on independent tasks (2× speedup) — but a chain of dependent steps can't be sped up by adding workers.",
    related: ["parallelism", "dependency-chain"], lessons: ["speedup"] },
  { slug: "dependency-chain", term: "Dependency chain", category: "complexity",
    short: "A sequence of steps that must run in order because each needs the previous result.",
    body: "Dependencies cap parallel speedup: if step B needs step A's output, no number of workers can make them overlap. The longest chain sets the floor on time.",
    related: ["parallelism", "speedup"], lessons: ["speedup"] },
];

// ---- helpers --------------------------------------------------------------------------------------
const _bySlug = Object.fromEntries(terms.map((t) => [t.slug, t]));

export function termBySlug(slug) {
  return _bySlug[slug] ?? null;
}
export function termsByCategory(category) {
  return terms.filter((t) => t.category === category);
}
export function allCategories() {
  return CATEGORY_ORDER.filter((c) => terms.some((t) => t.category === c));
}
export function relatedTermsOf(slug) {
  const t = _bySlug[slug];
  if (!t || !t.related) return [];
  return t.related.map((s) => _bySlug[s]).filter(Boolean);
}
// Lesson slugs a term appears in, returned as a lightweight {slug} list. The page resolves titles via
// curriculum.js lessonBySlug so there is one source of truth for lesson titles/URLs.
export function lessonSlugsForTerm(slug) {
  const t = _bySlug[slug];
  return t && t.lessons ? t.lessons : [];
}

// slug -> short definition, for the client-side popup (kept tiny: no bodies shipped to every page).
export const termsMap = Object.fromEntries(terms.map((t) => [t.slug, { term: t.term, short: t.short }]));
